drop schema "ecommerce-app";
CREATE SCHEMA "ecommerce-app"
    AUTHORIZATION ecommerceapp;

create table "ecommerce-app".product_category (
                                                  id bigint generated by default as identity primary key,
                                                  category_name varchar(255) not null default null
);

create table "ecommerce-app".product (
                                         id bigint generated by default as identity primary key,
                                         sku varchar(255) default null,
                                         name varchar(255) default null,
                                         description varchar(255) default null,
                                         unit_price decimal(13,2) default null,
                                         image_url varchar(255) default null,
                                         active bool default true,
                                         units_in_stock int default null,
                                         date_created timestamp(6) default null,
                                         last_updated timestamp(6) default null,
                                         category_id bigint not null references "ecommerce-app".product_category(id)
);

INSERT INTO "ecommerce-app".product_category(category_name) VALUES ('BOOKS');

INSERT INTO "ecommerce-app".product (sku, name, description, image_url, active, units_in_stock,
                                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1000', 'JavaScript - The Fun Parts', 'Learn JavaScript',
        'assets/images/products/placeholder.png'
           ,true,100,19.99,1, NOW());

INSERT INTO "ecommerce-app".product (sku, name, description, image_url, active, units_in_stock,
                                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1001', 'Spring Framework Tutorial', 'Learn Spring',
        'assets/images/products/placeholder.png'
           ,true,100,29.99,1, NOW());

INSERT INTO "ecommerce-app".product (sku, name, description, image_url, active, units_in_stock,
                                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1002', 'Kubernetes - Deploying Containers', 'Learn Kubernetes',
        'assets/images/products/placeholder.png'
           ,true,100,24.99,1, NOW());

INSERT INTO "ecommerce-app".product (sku, name, description, image_url, active, units_in_stock,
                                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1003', 'Internet of Things (IoT) - Getting Started', 'Learn IoT',
        'assets/images/products/placeholder.png'
           ,true,100,29.99,1, NOW());

INSERT INTO "ecommerce-app".product (sku, name, description, image_url, active, units_in_stock,
                                     unit_price, category_id, date_created)
VALUES ('BOOK-TECH-1004', 'The Go Programming Language: A to Z', 'Learn Go',
        'assets/images/products/placeholder.png'
           ,true,100,24.99,1, NOW());

select * from "ecommerce-app".product;