--
-- Table structure for table `address`
--
create table "ecommerce-app".address (
                                         id bigint generated by default as identity primary key,
                                         city varchar(255) default null,
                                         country varchar(255) default null,
                                         state varchar(255) default null,
                                         street varchar(255) default null,
                                         zip_code varchar(255) default null

);

--
-- Table structure for table `customer`
--
create table "ecommerce-app".customer (
                                          id bigint generated by default as identity primary key,
                                          first_name varchar(255) default null,
                                          last_name varchar(255) default null,
                                          email varchar(255) default null

);

--
-- Table structure for table `orders`
--
create table "ecommerce-app".orders (
                                        id bigint generated by default as identity primary key,
                                        order_tracking_number varchar(255) DEFAULT NULL,
                                        total_price decimal(19,2) DEFAULT NULL,
                                        total_quantity int DEFAULT NULL,
                                        billing_address_id bigint DEFAULT NULL,
                                        customer_id bigint DEFAULT NULL,
                                        shipping_address_id bigint DEFAULT NULL,
                                        status varchar(128) DEFAULT NULL,
                                        date_created timestamp(6) DEFAULT NULL,
                                        last_updated timestamp(6) DEFAULT NULL,
                                        CONSTRAINT FK_customer_id FOREIGN KEY (customer_id) REFERENCES "ecommerce-app".customer (id),
                                        CONSTRAINT FK_billing_address_id FOREIGN KEY (billing_address_id) REFERENCES "ecommerce-app".address (id),
                                        CONSTRAINT FK_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES "ecommerce-app".address (id)
);

--
-- Table structure for table `order_items`
--
CREATE TABLE "ecommerce-app".order_item (
                                            id bigint generated by default as identity primary key,
                                            image_url VARCHAR(255) default null,
                                            quantity int default null,
                                            unit_price numeric(19,2) default null,
                                            order_id bigint default null,
                                            product_id bigint default null,
                                            CONSTRAINT FK_order_id FOREIGN KEY (order_id) REFERENCES "ecommerce-app".orders (id),
                                            CONSTRAINT FK_product_id FOREIGN KEY (product_id) REFERENCES "ecommerce-app".product (id)
);
